note
	description: "Input Handler"
	author: ""
	date: "$Date$"
	revision: "$Revision$"

deferred class
	ETF_INPUT_HANDLER_INTERFACE
inherit
	ETF_TYPE_CONSTRAINTS

feature {NONE}

	make_without_running(etf_input: STRING; a_commands: ETF_ABSTRACT_UI_INTERFACE)
			-- convert an input string into array of commands
	  	do
	  		create on_error
		  	input_string := etf_input
		  	abstract_ui  := a_commands
	  	end

	make(etf_input: STRING; a_commands: ETF_ABSTRACT_UI_INTERFACE)
			-- convert an input string into array of commands
	  	do
	  		make_without_running(etf_input, a_commands)
			parse_and_validate_input_string
	  	end

feature -- auxiliary queries

	etf_evt_out (evt: TUPLE[name: STRING; args: ARRAY[ETF_EVT_ARG]]): STRING
		local
			etf_local_i: INTEGER
			name: STRING
			args: ARRAY[ETF_EVT_ARG]
		do
			name := evt.name
			args := evt.args
			create Result.make_empty
			Result.append (name + "(")
			from
				etf_local_i := args.lower
			until
				etf_local_i > args.upper
			loop
				if args[etf_local_i].src_out.is_empty then
					Result.append (args[etf_local_i].out)
				else
					Result.append (args[etf_local_i].src_out)
				end
				if etf_local_i < args.upper then
					Result.append (", ")
				end
				etf_local_i := etf_local_i + 1
			end
			Result.append (")")
		end

feature -- attributes

	etf_error: BOOLEAN

	input_string: STRING -- list of commands to execute

	abstract_ui: ETF_ABSTRACT_UI_INTERFACE
		-- output generated by `parse_string'

feature -- error reporting

	on_error: ETF_EVENT [TUPLE[STRING]]

feature -- error messages

	input_cmds_syntax_err_msg : STRING =
		"Syntax Error: specification of command executions cannot be parsed"

	input_cmds_type_err_msg : STRING =
		"Type Error: specification of command executions is not type-correct"

feature -- parsing

	parse_and_validate_input_string
	  local
		trace_parser : ETF_EVT_TRACE_PARSER
		cmd : ETF_COMMAND_INTERFACE
		invalid_cmds: STRING
	  do
		create trace_parser.make (evt_param_types_list, enum_items)
		trace_parser.parse_string (input_string)

	    if trace_parser.last_error.is_empty then
	  	  invalid_cmds := find_invalid_evt_trace (
		    	trace_parser.event_trace)
		  if invalid_cmds.is_empty then
		    across trace_parser.event_trace
		    as evt
		    loop
		      cmd := evt_to_cmd (evt.item)
		      abstract_ui.put (cmd)
		    end
		  else
		    etf_error := TRUE
		    on_error.notify (
		  	  input_cmds_type_err_msg + "%N" + invalid_cmds)
		  end
	    else
	      etf_error := TRUE
	      on_error.notify (
		    input_cmds_syntax_err_msg + "%N" + trace_parser.last_error)
	    end
	end

	evt_to_cmd (evt : TUPLE[name: STRING; args: ARRAY[ETF_EVT_ARG]]) : ETF_COMMAND_INTERFACE
		local
			cmd_name : STRING
			args : ARRAY[ETF_EVT_ARG]
			dummy_cmd : ETF_DUMMY
		do
			cmd_name := evt.name
			args := evt.args
			create dummy_cmd.make("dummy", [], abstract_ui)

			if cmd_name ~ "new_store" then 
				 if attached {ETF_INT_ARG} args[1] as xbound and then 0 <= xbound.value and then xbound.value <= 100 and then attached {ETF_INT_ARG} args[2] as ybound and then 0 <= ybound.value and then ybound.value <= 100 then 
					 create {ETF_NEW_STORE} Result.make ("new_store", [xbound.value , ybound.value], abstract_ui) 
				 else 
					 Result := dummy_cmd 
				 end 

			elseif cmd_name ~ "put" then 
				 if attached {ETF_STR_ARG} args[1] as id and then TRUE and then (attached {ETF_TUPLE_ARG} args[2] as explosive) and then explosive.value.count = 2 and then (attached {ETF_INT_ARG} explosive.value[1] as explosive_xlength) and then (attached {ETF_INT_ARG} explosive.value[2] as explosive_ylength) and then 0 <= explosive_xlength.value and then explosive_xlength.value <= 100 and then 0 <= explosive_ylength.value and then explosive_ylength.value <= 100 and then (attached {ETF_TUPLE_ARG} args[3] as position) and then position.value.count = 2 and then (attached {ETF_INT_ARG} position.value[1] as position_x) and then (attached {ETF_INT_ARG} position.value[2] as position_y) and then 0 <= position_x.value and then position_x.value <= 100 and then 0 <= position_y.value and then position_y.value <= 100 then 
					 create {ETF_PUT} Result.make ("put", [id.value , [explosive_xlength.value, explosive_ylength.value] , [position_x.value, position_y.value]], abstract_ui) 
				 else 
					 Result := dummy_cmd 
				 end 

			elseif cmd_name ~ "remove" then 
				 if attached {ETF_STR_ARG} args[1] as id and then TRUE then 
					 create {ETF_REMOVE} Result.make ("remove", [id.value], abstract_ui) 
				 else 
					 Result := dummy_cmd 
				 end 

			elseif cmd_name ~ "suggest" then 
				 if (attached {ETF_TUPLE_ARG} args[1] as explosive) and then explosive.value.count = 2 and then (attached {ETF_INT_ARG} explosive.value[1] as explosive_xlength) and then (attached {ETF_INT_ARG} explosive.value[2] as explosive_ylength) and then 0 <= explosive_xlength.value and then explosive_xlength.value <= 100 and then 0 <= explosive_ylength.value and then explosive_ylength.value <= 100 then 
					 create {ETF_SUGGEST} Result.make ("suggest", [[explosive_xlength.value, explosive_ylength.value]], abstract_ui) 
				 else 
					 Result := dummy_cmd 
				 end 

			elseif cmd_name ~ "large_explosives" then 
				 if attached {ETF_INT_ARG} args[1] as xlength and then 0 <= xlength.value and then xlength.value <= 100 and then attached {ETF_INT_ARG} args[2] as ylength and then 0 <= ylength.value and then ylength.value <= 100 then 
					 create {ETF_LARGE_EXPLOSIVES} Result.make ("large_explosives", [xlength.value , ylength.value], abstract_ui) 
				 else 
					 Result := dummy_cmd 
				 end 
			else 
				 Result := dummy_cmd 
			end 
		end

	find_invalid_evt_trace (
		event_trace: ARRAY[TUPLE[name: STRING; args: ARRAY[ETF_EVT_ARG]]])
	: STRING
	local
		loop_counter: INTEGER
		evt: TUPLE[name: STRING; args: ARRAY[ETF_EVT_ARG]]
		cmd_name: STRING
		args: ARRAY[ETF_EVT_ARG]
		evt_out_str: STRING
	do
		create Result.make_empty
		from
			loop_counter := event_trace.lower
		until
			loop_counter > event_trace.upper
		loop
			evt := event_trace[loop_counter]
			evt_out_str := etf_evt_out (evt)

			cmd_name := evt.name
			args := evt.args

			if cmd_name ~ "new_store" then 
				if NOT( ( args.count = 2 ) AND THEN attached {ETF_INT_ARG} args[1] as xbound and then 0 <= xbound.value and then xbound.value <= 100 and then attached {ETF_INT_ARG} args[2] as ybound and then 0 <= ybound.value and then ybound.value <= 100) then 
					if NOT Result.is_empty then
						Result.append ("%N")
					end
					Result.append (evt_out_str + " does not conform to declaration " +
							"new_store(xbound: UNIT = 0 .. 100 ; ybound: UNIT = 0 .. 100)")
				end

			elseif cmd_name ~ "put" then 
				if NOT( ( args.count = 3 ) AND THEN attached {ETF_STR_ARG} args[1] as id and then TRUE and then (attached {ETF_TUPLE_ARG} args[2] as explosive) and then explosive.value.count = 2 and then (attached {ETF_INT_ARG} explosive.value[1] as explosive_xlength) and then (attached {ETF_INT_ARG} explosive.value[2] as explosive_ylength) and then 0 <= explosive_xlength.value and then explosive_xlength.value <= 100 and then 0 <= explosive_ylength.value and then explosive_ylength.value <= 100 and then (attached {ETF_TUPLE_ARG} args[3] as position) and then position.value.count = 2 and then (attached {ETF_INT_ARG} position.value[1] as position_x) and then (attached {ETF_INT_ARG} position.value[2] as position_y) and then 0 <= position_x.value and then position_x.value <= 100 and then 0 <= position_y.value and then position_y.value <= 100) then 
					if NOT Result.is_empty then
						Result.append ("%N")
					end
					Result.append (evt_out_str + " does not conform to declaration " +
							"put(id: ID = STRING ; explosive: EXPLOSIVE = TUPLE[xlength: UNIT = 0 .. 100; ylength: UNIT = 0 .. 100] ; position: POSITION = TUPLE[x: UNIT = 0 .. 100; y: UNIT = 0 .. 100])")
				end

			elseif cmd_name ~ "remove" then 
				if NOT( ( args.count = 1 ) AND THEN attached {ETF_STR_ARG} args[1] as id and then TRUE) then 
					if NOT Result.is_empty then
						Result.append ("%N")
					end
					Result.append (evt_out_str + " does not conform to declaration " +
							"remove(id: ID = STRING)")
				end

			elseif cmd_name ~ "suggest" then 
				if NOT( ( args.count = 1 ) AND THEN (attached {ETF_TUPLE_ARG} args[1] as explosive) and then explosive.value.count = 2 and then (attached {ETF_INT_ARG} explosive.value[1] as explosive_xlength) and then (attached {ETF_INT_ARG} explosive.value[2] as explosive_ylength) and then 0 <= explosive_xlength.value and then explosive_xlength.value <= 100 and then 0 <= explosive_ylength.value and then explosive_ylength.value <= 100) then 
					if NOT Result.is_empty then
						Result.append ("%N")
					end
					Result.append (evt_out_str + " does not conform to declaration " +
							"suggest(explosive: EXPLOSIVE = TUPLE[xlength: UNIT = 0 .. 100; ylength: UNIT = 0 .. 100])")
				end

			elseif cmd_name ~ "large_explosives" then 
				if NOT( ( args.count = 2 ) AND THEN attached {ETF_INT_ARG} args[1] as xlength and then 0 <= xlength.value and then xlength.value <= 100 and then attached {ETF_INT_ARG} args[2] as ylength and then 0 <= ylength.value and then ylength.value <= 100) then 
					if NOT Result.is_empty then
						Result.append ("%N")
					end
					Result.append (evt_out_str + " does not conform to declaration " +
							"large_explosives(xlength: UNIT = 0 .. 100 ; ylength: UNIT = 0 .. 100)")
				end
			else
				if NOT Result.is_empty then
					Result.append ("%N")
				end
				Result.append ("Error: unknown event name " + cmd_name)
			end
			loop_counter := loop_counter + 1
		end
	end
end